language: java
sudo: false

jdk:
  - oraclejdkll
  
install:
  mvn clean install -Dskiptests=true
  
script:
  mvn -Dtest=SUTTest test -e 

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  keep_history: true
  on:
    branch: ruofan